{
  "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextDataList",
  "FileHeader" : {
    "MagicBytesLength" : 4,
    "MagicString" : "QTD\u0000",
    "VersionBytesLength" : 4,
    "VersionNumber" : 2
  },
  "FileSize" : 52,
  "QuestTextDataList" : [ {
    "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextData",
    "Message" : {
      "En" : "The Experiment Strikes Back",
      "Jp" : "実験動物の逆襲"
    },
    "MsgGmdIdx" : 0,
    "Type" : 0,
    "TypeName" : "QUEST_TEXT_TYPE_NAME"
  }, {
    "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextData",
    "Message" : {
      "En" : "Defeat encountered foe(s)",
      "Jp" : "遭遇した敵を討伐する"
    },
    "MsgGmdIdx" : 1,
    "Type" : 1,
    "TypeName" : "QUEST_TEXT_TYPE_ORDER"
  }, {
    "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextData",
    "Message" : {
      "En" : "According to reports from <NAME AREA>, \nenemy forces have temporarily increased, \nand the situation is quite dangerous.",
      "Jp" : "<NAME AREA>からの報告によると\n魔物の勢力が一時的に増し、危険な状況にあるという"
    },
    "MsgGmdIdx" : 2,
    "Type" : 3,
    "TypeName" : "QUEST_TEXT_TYPE_FIND_INFO"
  }, {
    "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextData",
    "Message" : {
      "En" : "Having fought through many battlefields \nand faced numerous monsters, \nit was my first time against such a creature. \nBe wary of its rapid attacks— \nyou can't be too cautious.",
      "Jp" : "これまで数多の戦場を駆け抜け\n多くの魔物と対峙してきたが\n初めてだったよ、あんな奴は\nとにかく奴の繰り出す素早い攻撃には\n用心しすぎることはない"
    },
    "MsgGmdIdx" : 3,
    "Type" : 4,
    "TypeName" : "QUEST_TEXT_TYPE_FIND_INFO_DETAIL"
  }, {
    "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextData",
    "Message" : {
      "En" : "Defeat encountered foe(s)",
      "Jp" : "遭遇した敵を討伐する"
    },
    "MsgGmdIdx" : 4,
    "Type" : 2,
    "TypeName" : "QUEST_TEXT_TYPE_PURPOSE"
  } ]
}